[build-system]
requires = ["maturin>=1.4,<2.0"]
build-backend = "maturin"

[project]
name = "ryl"
version = "0.1.0"
description = "Fast YAML linter (Rust) packaged for PyPI"
requires-python = ">=3.9"

[tool.maturin]
bindings = "bin"
sdist = true
