name: Pre-commit checks
on:
  pull_request:
jobs:
  pre-commit:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout repository
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8

      - name: Install uv
        uses: astral-sh/setup-uv@4959332f0f014c5280e7eac8b70c90cb574c9f9b

      - name: Install pre-commit globally
        run: uv tool install pre-commit --with pre-commit-uv --force

      - uses: Swatinem/rust-cache@98c8021b550208e191a6a3145459bfc9fb29c4c0 # v2.8.0

      - name: "Install Rust toolchain"
        run: rustup component add rustfmt clippy

      - name: "Install cargo nextest"
        uses: taiki-e/install-action@14083e64ac8cf1f5e54356df00b9779b23e192a1 # v2.58.29
        with:
          tool: cargo-nextest

      - name: Run pre-commit hooks
        env:
          SKIP: no-commit-to-branch  # Skip the main branch protection hook in CI
        run: pre-commit run --all-files
